# Generated by Django 3.2.12 on 2023-07-22 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_expense_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='pay_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pay_user', to='master.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='user_distributed',
            field=models.ManyToManyField(related_name='user_distributed', to=settings.AUTH_USER_MODEL),
        ),
    ]
