# Generated by Django 3.2.12 on 2023-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_complete',
            field=models.BooleanField(default=False),
        ),
    ]
