# Generated by Django 3.2.12 on 2023-08-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
