# Generated by Django 3.2.12 on 2023-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_faqcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
