# Generated by Django 3.2.12 on 2023-08-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_remove_faqcategory_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
    ]
